version: "3"

networks:
  my_network:

services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run build && npm run dev"
    ports:
      - 8000:8000
    working_dir: /app
    networks:
      - my_network
    volumes:
      - ./:/app
    environment:
      DB_HOST: localhost
      DB_USERNAME: root
      DB_PASSWORD: .caerux
      DB_DATABASE: node_base
      DB_PORT: 3306
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: node_base
      MARIADB_USER: caerux
      MARIADB_PASSWORD: .caerux
      MARIADB_ROOT_PASSWORD: .caerux
      SERVICE_NAME: mariadb
    networks:
      - my_network
